Repository 9oormthon-univ/2025_SEASONTHON_TEAM_94_FE_WEB, pull requests merged in 2025-09, with the labels that each got.

#5 Refactor: tanstack-qeury 적용, 코드 리팩토링
  .github/copilot-instructions.md
  app/app.css
  app/components/calendar-32.tsx
  app/features/expenses/_lib/types/hooks.ts
  app/features/expenses/_lib/types/index.ts
  app/features/expenses/_lib/validation.ts
  app/features/expenses/api/queryKeys.ts
  app/features/expenses/components/ExpenseDetail.tsx
  app/features/expenses/components/ExpenseForm.tsx
  app/features/expenses/components/ExpenseHeader.tsx
  app/features/expenses/components/Form/ExpenseForm.tsx
  app/features/expenses/components/Form/ExpenseTypeSelector.tsx
  app/features/expenses/components/Form/FormField.tsx
  app/features/expenses/components/Form/PriceInput.tsx
  app/features/expenses/components/List/CategorizedExpenseList.tsx
  app/features/expenses/components/List/UncategorizedExpenseList.tsx
  app/features/expenses/components/PriceInput.tsx
  app/features/expenses/hooks/index.ts
  app/features/expenses/hooks/useExpenseForm.ts
  app/features/expenses/hooks/useExpenseMutations.ts
  app/features/expenses/hooks/useExpenseQueries.ts
  app/features/expenses/hooks/useExpenses.tsx
  app/features/expenses/index.ts
  app/features/expenses/pages/ExpenseAddPage.tsx
  app/features/expenses/pages/ExpenseDetailPage.tsx
  app/features/expenses/pages/ExpensesPage.tsx
  app/features/expenses/utils/expenseUtils.ts
  app/features/more/pages/MorePage.tsx
  app/features/reports/pages/BudgetGoalPage.tsx
  app/features/reports/pages/ReportsPage.tsx
  app/root.tsx
  app/shared/components/Header.tsx
  app/shared/components/ui/drawer.tsx
  app/shared/components/ui/skeleton.tsx
  app/shared/hooks/useCursorPosition.ts
  app/shared/hooks/useHideNav.ts
  app/shared/index.ts
  app/shared/providers/QueryProvider.tsx
  components.json
  package.json
  pnpm-lock.yaml
Labels: Type:UI, Type: Refactor

#8 refactor: 지출 생성/수정 페이지 변경
  app/app.css
  app/assets/Chevron_down.svg
  app/assets/Chevron_up.svg
  app/assets/category/cafe.svg
  app/assets/category/convenience_store.svg
  app/assets/category/culture.svg
  app/assets/category/dues.svg
  app/assets/category/essentials.svg
  app/assets/category/etc.svg
  app/assets/category/fashion.svg
  app/assets/category/food.svg
  app/assets/category/furniture.svg
  app/assets/category/growth.svg
  app/assets/category/transit.svg
  app/assets/category/utilities.svg
  app/assets/fonts/PretendardVariable.woff2
  app/features/expenses/_lib/types/components.ts
  app/features/expenses/_lib/validation.ts
  app/features/expenses/api/expenseApi.ts
  app/features/expenses/components/ExpenseHeader.tsx
  app/features/expenses/components/Form/CategorySelector.tsx
  app/features/expenses/components/Form/ExpenseForm.tsx
  app/features/expenses/components/Form/ExpenseTypeSelector.tsx
  app/features/expenses/components/Form/FormField.tsx
  app/features/expenses/components/Form/InputField.tsx
  app/features/expenses/components/Form/NumberStepper.tsx
  app/features/expenses/components/Form/PriceInput.tsx
  app/features/expenses/components/List/CategorizedExpenseList.tsx
  app/features/expenses/components/List/UncategorizedExpenseList.tsx
  app/features/expenses/hooks/useExpenseForm.ts
  app/features/expenses/hooks/useExpenseMutations.ts
  app/features/expenses/hooks/useExpenseQueries.ts
  app/features/expenses/index.ts
  app/features/expenses/pages/ExpenseAddPage.tsx
  app/features/expenses/pages/ExpenseDetailPage.tsx
  app/features/expenses/pages/ExpensesPage.tsx
  app/features/expenses/utils/expenseUtils.ts
  app/features/expenses/utils/formUtils.ts
  app/shared/components/ui/input.tsx
  app/shared/config/api.ts
  app/shared/types/api.ts
  app/shared/types/budget.ts
  app/shared/types/expense.ts
  app/shared/types/user.ts
Labels: Type:UI, Type: Refactor

#11 refactor(profile): 프로필 디자인 반영
  app/assets/goal.svg
  app/assets/nickname.svg
  app/assets/right.svg
  app/assets/warning.svg
  app/features/home/hooks/useHome.ts
  app/features/more/api/index.ts
  app/features/more/api/transactions.ts
  app/features/more/api/user.ts
  app/features/more/components/LogoutConfirm.tsx
  app/features/more/components/MiniReport.tsx
  app/features/more/components/ProfileCard.tsx
  app/features/more/pages/MorePage.tsx
  app/features/profile/api/user.ts
  app/features/profile/components/LogoutConfirm.tsx
  app/features/profile/components/ProfileHeader.tsx
  app/features/profile/hooks/useNickname.ts
  app/features/profile/pages/NicknamePage.tsx
  app/features/profile/pages/ProfilePage.tsx
  app/features/reports/api/budgetGoals.ts
  app/features/reports/components/ProgressBar.tsx
  app/features/reports/hooks/useBudgetGoal.ts
  app/features/reports/hooks/useReport.ts
  app/routes.ts
  app/routes/more.tsx
  app/routes/profile.tsx
  mkcert/cert.pem
  mkcert/key.pem
  package-lock.json
Labels: Type:UI, Type: Refactor, Type: Feature

#14 feat(native): 네이티브 통신처리 및 디자인 미세 조정
  app/assets/pencil.svg
  app/components/calendar-32.tsx
  app/features/auth/components/AuthGuard.tsx
  app/features/auth/hooks/useAuthCallback.ts
  app/features/auth/pages/AuthCallbackPage.tsx
  app/features/auth/pages/AuthPage.tsx
  app/features/calendar/pages/ExpensesCalendarPage.tsx
  app/features/expenses/components/ExpenseDetail.tsx
  app/features/expenses/components/Form/CategorySelector.tsx
  app/features/expenses/components/Form/ExpenseTypeSelector.tsx
  app/features/expenses/components/Form/InputField.tsx
  app/features/expenses/components/Form/NumberStepper.tsx
  app/features/expenses/components/List/BulkActionButtons.tsx
  app/features/expenses/components/List/UncategorizedExpenseItem.tsx
  app/features/expenses/index.ts
  app/features/expenses/pages/ExpenseAddPage.tsx
  app/features/expenses/pages/ExpenseDetailPage.tsx
  app/features/expenses/pages/ExpenseFixed.tsx
  app/features/expenses/pages/ExpenseOver.tsx
  app/features/expenses/pages/ExpenseUnclassified.tsx
  app/features/expenses/pages/ExpensesPage.tsx
  app/features/home/components/ExpenseCard.tsx
  app/features/home/components/HomeSummary.tsx
  app/features/home/pages/HomePage.tsx
  app/features/onboarding/hooks/useBudgetGoalForm.ts
  app/features/onboarding/hooks/useBudgetGoalMutation.ts
  app/features/onboarding/hooks/useNicknameMutation.ts
  app/features/onboarding/pages/budget-goal.tsx
  app/features/onboarding/pages/nickname.tsx
  app/features/profile/components/LogoutConfirm.tsx
  app/features/profile/components/NicknameForm.tsx
  app/features/profile/components/ProfileHeader.tsx
  app/features/profile/hooks/useNickname.ts
  app/features/profile/pages/NicknamePage.tsx
  app/features/profile/pages/ProfilePage.tsx
  app/features/reports/components/BudgetGoalForm.tsx
  app/features/reports/components/ReportSummary.tsx
  app/features/reports/hooks/useReport.ts
  app/features/reports/pages/BudgetGoalPage.tsx
  app/features/reports/pages/ReportsPage.tsx
  app/routes.ts
  app/routes/expenses._index.tsx
  app/routes/not-found.tsx
  app/shared/components/BottomNav.tsx
  app/shared/components/ui/input.tsx
  app/shared/components/wheel-picker.tsx
  app/shared/utils/nativeBridge.ts
Labels: Type:UI, Type: Refactor, Type: Feature

#18 refactor: 바텀탭 애니메이션 추가
  app/shared/components/BottomNav.tsx
Labels: Type:UI, Type: Refactor

#23 fix: onKeyDown, 추가 후 라우팅 처리 등
  app/features/expenses/components/Form/ExpenseForm.tsx
  app/features/expenses/components/Form/NumberStepper.tsx
  app/features/expenses/components/List/FixedExpenseItem.tsx
  app/features/expenses/components/List/OverExpenseItem.tsx
  app/features/expenses/components/List/UncategorizedExpenseItem.tsx
  app/features/expenses/pages/ExpenseAddPage.tsx
  app/features/expenses/pages/ExpenseDetailPage.tsx
  app/features/expenses/utils/calculationUtils.ts
  app/features/home/components/HomeSummary.tsx
  app/features/home/hooks/useHome.ts
  app/features/home/pages/HomePage.tsx
  app/features/onboarding/hooks/useBudgetGoalForm.ts
  app/features/onboarding/pages/budget-goal.tsx
  app/features/onboarding/utils/amountUtils.ts
  mkcert/cert.pem
  mkcert/key.pem
  package.json
Labels: Type: BugFix, Type: Refactor

#25 refactor: 프로그레스바 애니메이션 추가
  app/features/reports/components/ProgressBar.tsx
Labels: Type:UI, Type: Refactor
